#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nesneOtomasyon
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="rentAcar")]
	public partial class baglantiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkira(kira instance);
    partial void Updatekira(kira instance);
    partial void Deletekira(kira instance);
    partial void Insertmarka(marka instance);
    partial void Updatemarka(marka instance);
    partial void Deletemarka(marka instance);
    partial void Insertaraba(araba instance);
    partial void Updatearaba(araba instance);
    partial void Deletearaba(araba instance);
    partial void Insertodeme(odeme instance);
    partial void Updateodeme(odeme instance);
    partial void Deleteodeme(odeme instance);
    partial void Insertmusteri(musteri instance);
    partial void Updatemusteri(musteri instance);
    partial void Deletemusteri(musteri instance);
    #endregion
		
		public baglantiDataContext() : 
				base(global::nesneOtomasyon.Properties.Settings.Default.rentAcarConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public baglantiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baglantiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baglantiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baglantiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<kira> kiras
		{
			get
			{
				return this.GetTable<kira>();
			}
		}
		
		public System.Data.Linq.Table<marka> markas
		{
			get
			{
				return this.GetTable<marka>();
			}
		}
		
		public System.Data.Linq.Table<araba> arabas
		{
			get
			{
				return this.GetTable<araba>();
			}
		}
		
		public System.Data.Linq.Table<odeme> odemes
		{
			get
			{
				return this.GetTable<odeme>();
			}
		}
		
		public System.Data.Linq.Table<musteri> musteris
		{
			get
			{
				return this.GetTable<musteri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kira")]
	public partial class kira : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kiraNo;
		
		private string _plakaNo;
		
		private string _kimlikNo;
		
		private System.Nullable<System.DateTime> _kiraTarih;
		
		private System.Nullable<System.DateTime> _gelisTarih;
		
		private string _hasarDurum;
		
		private string _durum;
		
		private EntitySet<odeme> _odemes;
		
		private EntityRef<araba> _araba;
		
		private EntityRef<musteri> _musteri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkiraNoChanging(int value);
    partial void OnkiraNoChanged();
    partial void OnplakaNoChanging(string value);
    partial void OnplakaNoChanged();
    partial void OnkimlikNoChanging(string value);
    partial void OnkimlikNoChanged();
    partial void OnkiraTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnkiraTarihChanged();
    partial void OngelisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OngelisTarihChanged();
    partial void OnhasarDurumChanging(string value);
    partial void OnhasarDurumChanged();
    partial void OndurumChanging(string value);
    partial void OndurumChanged();
    #endregion
		
		public kira()
		{
			this._odemes = new EntitySet<odeme>(new Action<odeme>(this.attach_odemes), new Action<odeme>(this.detach_odemes));
			this._araba = default(EntityRef<araba>);
			this._musteri = default(EntityRef<musteri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kiraNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kiraNo
		{
			get
			{
				return this._kiraNo;
			}
			set
			{
				if ((this._kiraNo != value))
				{
					this.OnkiraNoChanging(value);
					this.SendPropertyChanging();
					this._kiraNo = value;
					this.SendPropertyChanged("kiraNo");
					this.OnkiraNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plakaNo", DbType="NChar(9)")]
		public string plakaNo
		{
			get
			{
				return this._plakaNo;
			}
			set
			{
				if ((this._plakaNo != value))
				{
					if (this._araba.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnplakaNoChanging(value);
					this.SendPropertyChanging();
					this._plakaNo = value;
					this.SendPropertyChanged("plakaNo");
					this.OnplakaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kimlikNo", DbType="NChar(11)")]
		public string kimlikNo
		{
			get
			{
				return this._kimlikNo;
			}
			set
			{
				if ((this._kimlikNo != value))
				{
					if (this._musteri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkimlikNoChanging(value);
					this.SendPropertyChanging();
					this._kimlikNo = value;
					this.SendPropertyChanged("kimlikNo");
					this.OnkimlikNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kiraTarih", DbType="Date")]
		public System.Nullable<System.DateTime> kiraTarih
		{
			get
			{
				return this._kiraTarih;
			}
			set
			{
				if ((this._kiraTarih != value))
				{
					this.OnkiraTarihChanging(value);
					this.SendPropertyChanging();
					this._kiraTarih = value;
					this.SendPropertyChanged("kiraTarih");
					this.OnkiraTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gelisTarih", DbType="Date")]
		public System.Nullable<System.DateTime> gelisTarih
		{
			get
			{
				return this._gelisTarih;
			}
			set
			{
				if ((this._gelisTarih != value))
				{
					this.OngelisTarihChanging(value);
					this.SendPropertyChanging();
					this._gelisTarih = value;
					this.SendPropertyChanged("gelisTarih");
					this.OngelisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasarDurum", DbType="VarChar(150)")]
		public string hasarDurum
		{
			get
			{
				return this._hasarDurum;
			}
			set
			{
				if ((this._hasarDurum != value))
				{
					this.OnhasarDurumChanging(value);
					this.SendPropertyChanging();
					this._hasarDurum = value;
					this.SendPropertyChanged("hasarDurum");
					this.OnhasarDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durum", DbType="NVarChar(1)")]
		public string durum
		{
			get
			{
				return this._durum;
			}
			set
			{
				if ((this._durum != value))
				{
					this.OndurumChanging(value);
					this.SendPropertyChanging();
					this._durum = value;
					this.SendPropertyChanged("durum");
					this.OndurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kira_odeme", Storage="_odemes", ThisKey="kiraNo", OtherKey="kiraNo")]
		public EntitySet<odeme> odemes
		{
			get
			{
				return this._odemes;
			}
			set
			{
				this._odemes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="araba_kira", Storage="_araba", ThisKey="plakaNo", OtherKey="plakaNo", IsForeignKey=true)]
		public araba araba
		{
			get
			{
				return this._araba.Entity;
			}
			set
			{
				araba previousValue = this._araba.Entity;
				if (((previousValue != value) 
							|| (this._araba.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._araba.Entity = null;
						previousValue.kiras.Remove(this);
					}
					this._araba.Entity = value;
					if ((value != null))
					{
						value.kiras.Add(this);
						this._plakaNo = value.plakaNo;
					}
					else
					{
						this._plakaNo = default(string);
					}
					this.SendPropertyChanged("araba");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="musteri_kira", Storage="_musteri", ThisKey="kimlikNo", OtherKey="kimlikNo", IsForeignKey=true)]
		public musteri musteri
		{
			get
			{
				return this._musteri.Entity;
			}
			set
			{
				musteri previousValue = this._musteri.Entity;
				if (((previousValue != value) 
							|| (this._musteri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._musteri.Entity = null;
						previousValue.kiras.Remove(this);
					}
					this._musteri.Entity = value;
					if ((value != null))
					{
						value.kiras.Add(this);
						this._kimlikNo = value.kimlikNo;
					}
					else
					{
						this._kimlikNo = default(string);
					}
					this.SendPropertyChanged("musteri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_odemes(odeme entity)
		{
			this.SendPropertyChanging();
			entity.kira = this;
		}
		
		private void detach_odemes(odeme entity)
		{
			this.SendPropertyChanging();
			entity.kira = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.marka")]
	public partial class marka : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _markaNo;
		
		private string _markaAdi;
		
		private EntitySet<araba> _arabas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmarkaNoChanging(int value);
    partial void OnmarkaNoChanged();
    partial void OnmarkaAdiChanging(string value);
    partial void OnmarkaAdiChanged();
    #endregion
		
		public marka()
		{
			this._arabas = new EntitySet<araba>(new Action<araba>(this.attach_arabas), new Action<araba>(this.detach_arabas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_markaNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int markaNo
		{
			get
			{
				return this._markaNo;
			}
			set
			{
				if ((this._markaNo != value))
				{
					this.OnmarkaNoChanging(value);
					this.SendPropertyChanging();
					this._markaNo = value;
					this.SendPropertyChanged("markaNo");
					this.OnmarkaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_markaAdi", DbType="VarChar(50)")]
		public string markaAdi
		{
			get
			{
				return this._markaAdi;
			}
			set
			{
				if ((this._markaAdi != value))
				{
					this.OnmarkaAdiChanging(value);
					this.SendPropertyChanging();
					this._markaAdi = value;
					this.SendPropertyChanged("markaAdi");
					this.OnmarkaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="marka_araba", Storage="_arabas", ThisKey="markaNo", OtherKey="markaNo")]
		public EntitySet<araba> arabas
		{
			get
			{
				return this._arabas;
			}
			set
			{
				this._arabas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_arabas(araba entity)
		{
			this.SendPropertyChanging();
			entity.marka = this;
		}
		
		private void detach_arabas(araba entity)
		{
			this.SendPropertyChanging();
			entity.marka = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.araba")]
	public partial class araba : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _plakaNo;
		
		private string _ruhsatNo;
		
		private System.Nullable<int> _markaNo;
		
		private string _cins;
		
		private string _model;
		
		private string _yakit;
		
		private string _sase;
		
		private System.Nullable<System.DateTime> _sigortaTarih;
		
		private System.Nullable<System.DateTime> _kaskoTarih;
		
		private System.Nullable<System.DateTime> _vizeTarih;
		
		private string _band;
		
		private string _aciklama;
		
		private string _silmeDurum;
		
		private EntitySet<kira> _kiras;
		
		private EntityRef<marka> _marka;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnplakaNoChanging(string value);
    partial void OnplakaNoChanged();
    partial void OnruhsatNoChanging(string value);
    partial void OnruhsatNoChanged();
    partial void OnmarkaNoChanging(System.Nullable<int> value);
    partial void OnmarkaNoChanged();
    partial void OncinsChanging(string value);
    partial void OncinsChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnyakitChanging(string value);
    partial void OnyakitChanged();
    partial void OnsaseChanging(string value);
    partial void OnsaseChanged();
    partial void OnsigortaTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnsigortaTarihChanged();
    partial void OnkaskoTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnkaskoTarihChanged();
    partial void OnvizeTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnvizeTarihChanged();
    partial void OnbandChanging(string value);
    partial void OnbandChanged();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    partial void OnsilmeDurumChanging(string value);
    partial void OnsilmeDurumChanged();
    #endregion
		
		public araba()
		{
			this._kiras = new EntitySet<kira>(new Action<kira>(this.attach_kiras), new Action<kira>(this.detach_kiras));
			this._marka = default(EntityRef<marka>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plakaNo", DbType="NChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string plakaNo
		{
			get
			{
				return this._plakaNo;
			}
			set
			{
				if ((this._plakaNo != value))
				{
					this.OnplakaNoChanging(value);
					this.SendPropertyChanging();
					this._plakaNo = value;
					this.SendPropertyChanged("plakaNo");
					this.OnplakaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruhsatNo", DbType="NChar(6)")]
		public string ruhsatNo
		{
			get
			{
				return this._ruhsatNo;
			}
			set
			{
				if ((this._ruhsatNo != value))
				{
					this.OnruhsatNoChanging(value);
					this.SendPropertyChanging();
					this._ruhsatNo = value;
					this.SendPropertyChanged("ruhsatNo");
					this.OnruhsatNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_markaNo", DbType="Int")]
		public System.Nullable<int> markaNo
		{
			get
			{
				return this._markaNo;
			}
			set
			{
				if ((this._markaNo != value))
				{
					if (this._marka.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmarkaNoChanging(value);
					this.SendPropertyChanging();
					this._markaNo = value;
					this.SendPropertyChanged("markaNo");
					this.OnmarkaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cins", DbType="VarChar(50)")]
		public string cins
		{
			get
			{
				return this._cins;
			}
			set
			{
				if ((this._cins != value))
				{
					this.OncinsChanging(value);
					this.SendPropertyChanging();
					this._cins = value;
					this.SendPropertyChanged("cins");
					this.OncinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="NChar(4)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yakit", DbType="VarChar(50)")]
		public string yakit
		{
			get
			{
				return this._yakit;
			}
			set
			{
				if ((this._yakit != value))
				{
					this.OnyakitChanging(value);
					this.SendPropertyChanging();
					this._yakit = value;
					this.SendPropertyChanged("yakit");
					this.OnyakitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sase", DbType="NChar(20)")]
		public string sase
		{
			get
			{
				return this._sase;
			}
			set
			{
				if ((this._sase != value))
				{
					this.OnsaseChanging(value);
					this.SendPropertyChanging();
					this._sase = value;
					this.SendPropertyChanged("sase");
					this.OnsaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sigortaTarih", DbType="Date")]
		public System.Nullable<System.DateTime> sigortaTarih
		{
			get
			{
				return this._sigortaTarih;
			}
			set
			{
				if ((this._sigortaTarih != value))
				{
					this.OnsigortaTarihChanging(value);
					this.SendPropertyChanging();
					this._sigortaTarih = value;
					this.SendPropertyChanged("sigortaTarih");
					this.OnsigortaTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kaskoTarih", DbType="Date")]
		public System.Nullable<System.DateTime> kaskoTarih
		{
			get
			{
				return this._kaskoTarih;
			}
			set
			{
				if ((this._kaskoTarih != value))
				{
					this.OnkaskoTarihChanging(value);
					this.SendPropertyChanging();
					this._kaskoTarih = value;
					this.SendPropertyChanged("kaskoTarih");
					this.OnkaskoTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vizeTarih", DbType="Date")]
		public System.Nullable<System.DateTime> vizeTarih
		{
			get
			{
				return this._vizeTarih;
			}
			set
			{
				if ((this._vizeTarih != value))
				{
					this.OnvizeTarihChanging(value);
					this.SendPropertyChanging();
					this._vizeTarih = value;
					this.SendPropertyChanged("vizeTarih");
					this.OnvizeTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_band", DbType="NChar(15)")]
		public string band
		{
			get
			{
				return this._band;
			}
			set
			{
				if ((this._band != value))
				{
					this.OnbandChanging(value);
					this.SendPropertyChanging();
					this._band = value;
					this.SendPropertyChanged("band");
					this.OnbandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="VarChar(250)")]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this.OnaciklamaChanging(value);
					this.SendPropertyChanging();
					this._aciklama = value;
					this.SendPropertyChanged("aciklama");
					this.OnaciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_silmeDurum", DbType="VarChar(1)")]
		public string silmeDurum
		{
			get
			{
				return this._silmeDurum;
			}
			set
			{
				if ((this._silmeDurum != value))
				{
					this.OnsilmeDurumChanging(value);
					this.SendPropertyChanging();
					this._silmeDurum = value;
					this.SendPropertyChanged("silmeDurum");
					this.OnsilmeDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="araba_kira", Storage="_kiras", ThisKey="plakaNo", OtherKey="plakaNo")]
		public EntitySet<kira> kiras
		{
			get
			{
				return this._kiras;
			}
			set
			{
				this._kiras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="marka_araba", Storage="_marka", ThisKey="markaNo", OtherKey="markaNo", IsForeignKey=true)]
		public marka marka
		{
			get
			{
				return this._marka.Entity;
			}
			set
			{
				marka previousValue = this._marka.Entity;
				if (((previousValue != value) 
							|| (this._marka.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._marka.Entity = null;
						previousValue.arabas.Remove(this);
					}
					this._marka.Entity = value;
					if ((value != null))
					{
						value.arabas.Add(this);
						this._markaNo = value.markaNo;
					}
					else
					{
						this._markaNo = default(Nullable<int>);
					}
					this.SendPropertyChanged("marka");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kiras(kira entity)
		{
			this.SendPropertyChanging();
			entity.araba = this;
		}
		
		private void detach_kiras(kira entity)
		{
			this.SendPropertyChanging();
			entity.araba = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.odeme")]
	public partial class odeme : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _odemeNo;
		
		private System.Nullable<int> _kiraNo;
		
		private string _kimlikNo;
		
		private System.Nullable<int> _odemeTutar;
		
		private System.Nullable<char> _odemeSekli;
		
		private EntityRef<kira> _kira;
		
		private EntityRef<musteri> _musteri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnodemeNoChanging(int value);
    partial void OnodemeNoChanged();
    partial void OnkiraNoChanging(System.Nullable<int> value);
    partial void OnkiraNoChanged();
    partial void OnkimlikNoChanging(string value);
    partial void OnkimlikNoChanged();
    partial void OnodemeTutarChanging(System.Nullable<int> value);
    partial void OnodemeTutarChanged();
    partial void OnodemeSekliChanging(System.Nullable<char> value);
    partial void OnodemeSekliChanged();
    #endregion
		
		public odeme()
		{
			this._kira = default(EntityRef<kira>);
			this._musteri = default(EntityRef<musteri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odemeNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int odemeNo
		{
			get
			{
				return this._odemeNo;
			}
			set
			{
				if ((this._odemeNo != value))
				{
					this.OnodemeNoChanging(value);
					this.SendPropertyChanging();
					this._odemeNo = value;
					this.SendPropertyChanged("odemeNo");
					this.OnodemeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kiraNo", DbType="Int")]
		public System.Nullable<int> kiraNo
		{
			get
			{
				return this._kiraNo;
			}
			set
			{
				if ((this._kiraNo != value))
				{
					if (this._kira.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkiraNoChanging(value);
					this.SendPropertyChanging();
					this._kiraNo = value;
					this.SendPropertyChanged("kiraNo");
					this.OnkiraNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kimlikNo", DbType="NChar(11)")]
		public string kimlikNo
		{
			get
			{
				return this._kimlikNo;
			}
			set
			{
				if ((this._kimlikNo != value))
				{
					if (this._musteri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkimlikNoChanging(value);
					this.SendPropertyChanging();
					this._kimlikNo = value;
					this.SendPropertyChanged("kimlikNo");
					this.OnkimlikNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odemeTutar", DbType="Int")]
		public System.Nullable<int> odemeTutar
		{
			get
			{
				return this._odemeTutar;
			}
			set
			{
				if ((this._odemeTutar != value))
				{
					this.OnodemeTutarChanging(value);
					this.SendPropertyChanging();
					this._odemeTutar = value;
					this.SendPropertyChanged("odemeTutar");
					this.OnodemeTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odemeSekli", DbType="NChar(1)")]
		public System.Nullable<char> odemeSekli
		{
			get
			{
				return this._odemeSekli;
			}
			set
			{
				if ((this._odemeSekli != value))
				{
					this.OnodemeSekliChanging(value);
					this.SendPropertyChanging();
					this._odemeSekli = value;
					this.SendPropertyChanged("odemeSekli");
					this.OnodemeSekliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kira_odeme", Storage="_kira", ThisKey="kiraNo", OtherKey="kiraNo", IsForeignKey=true)]
		public kira kira
		{
			get
			{
				return this._kira.Entity;
			}
			set
			{
				kira previousValue = this._kira.Entity;
				if (((previousValue != value) 
							|| (this._kira.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kira.Entity = null;
						previousValue.odemes.Remove(this);
					}
					this._kira.Entity = value;
					if ((value != null))
					{
						value.odemes.Add(this);
						this._kiraNo = value.kiraNo;
					}
					else
					{
						this._kiraNo = default(Nullable<int>);
					}
					this.SendPropertyChanged("kira");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="musteri_odeme", Storage="_musteri", ThisKey="kimlikNo", OtherKey="kimlikNo", IsForeignKey=true)]
		public musteri musteri
		{
			get
			{
				return this._musteri.Entity;
			}
			set
			{
				musteri previousValue = this._musteri.Entity;
				if (((previousValue != value) 
							|| (this._musteri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._musteri.Entity = null;
						previousValue.odemes.Remove(this);
					}
					this._musteri.Entity = value;
					if ((value != null))
					{
						value.odemes.Add(this);
						this._kimlikNo = value.kimlikNo;
					}
					else
					{
						this._kimlikNo = default(string);
					}
					this.SendPropertyChanged("musteri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.musteri")]
	public partial class musteri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _kimlikNo;
		
		private string _adSoyad;
		
		private System.Nullable<System.DateTime> _dogumTarih;
		
		private string _adres;
		
		private string _email;
		
		private string _babaAdi;
		
		private string _kanGrup;
		
		private string _ehliyetNo;
		
		private string _ehliyetTip;
		
		private System.Nullable<System.DateTime> _ehliyetTarih;
		
		private string _telefon;
		
		private string _silmeDurumu;
		
		private EntitySet<kira> _kiras;
		
		private EntitySet<odeme> _odemes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkimlikNoChanging(string value);
    partial void OnkimlikNoChanged();
    partial void OnadSoyadChanging(string value);
    partial void OnadSoyadChanged();
    partial void OndogumTarihChanging(System.Nullable<System.DateTime> value);
    partial void OndogumTarihChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnbabaAdiChanging(string value);
    partial void OnbabaAdiChanged();
    partial void OnkanGrupChanging(string value);
    partial void OnkanGrupChanged();
    partial void OnehliyetNoChanging(string value);
    partial void OnehliyetNoChanged();
    partial void OnehliyetTipChanging(string value);
    partial void OnehliyetTipChanged();
    partial void OnehliyetTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnehliyetTarihChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void OnsilmeDurumuChanging(string value);
    partial void OnsilmeDurumuChanged();
    #endregion
		
		public musteri()
		{
			this._kiras = new EntitySet<kira>(new Action<kira>(this.attach_kiras), new Action<kira>(this.detach_kiras));
			this._odemes = new EntitySet<odeme>(new Action<odeme>(this.attach_odemes), new Action<odeme>(this.detach_odemes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kimlikNo", DbType="NChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string kimlikNo
		{
			get
			{
				return this._kimlikNo;
			}
			set
			{
				if ((this._kimlikNo != value))
				{
					this.OnkimlikNoChanging(value);
					this.SendPropertyChanging();
					this._kimlikNo = value;
					this.SendPropertyChanged("kimlikNo");
					this.OnkimlikNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adSoyad", DbType="VarChar(250)")]
		public string adSoyad
		{
			get
			{
				return this._adSoyad;
			}
			set
			{
				if ((this._adSoyad != value))
				{
					this.OnadSoyadChanging(value);
					this.SendPropertyChanging();
					this._adSoyad = value;
					this.SendPropertyChanged("adSoyad");
					this.OnadSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dogumTarih", DbType="Date")]
		public System.Nullable<System.DateTime> dogumTarih
		{
			get
			{
				return this._dogumTarih;
			}
			set
			{
				if ((this._dogumTarih != value))
				{
					this.OndogumTarihChanging(value);
					this.SendPropertyChanging();
					this._dogumTarih = value;
					this.SendPropertyChanged("dogumTarih");
					this.OndogumTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="VarChar(250)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_babaAdi", DbType="VarChar(70)")]
		public string babaAdi
		{
			get
			{
				return this._babaAdi;
			}
			set
			{
				if ((this._babaAdi != value))
				{
					this.OnbabaAdiChanging(value);
					this.SendPropertyChanging();
					this._babaAdi = value;
					this.SendPropertyChanged("babaAdi");
					this.OnbabaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kanGrup", DbType="VarChar(5)")]
		public string kanGrup
		{
			get
			{
				return this._kanGrup;
			}
			set
			{
				if ((this._kanGrup != value))
				{
					this.OnkanGrupChanging(value);
					this.SendPropertyChanging();
					this._kanGrup = value;
					this.SendPropertyChanged("kanGrup");
					this.OnkanGrupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ehliyetNo", DbType="NChar(5)")]
		public string ehliyetNo
		{
			get
			{
				return this._ehliyetNo;
			}
			set
			{
				if ((this._ehliyetNo != value))
				{
					this.OnehliyetNoChanging(value);
					this.SendPropertyChanging();
					this._ehliyetNo = value;
					this.SendPropertyChanged("ehliyetNo");
					this.OnehliyetNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ehliyetTip", DbType="VarChar(2)")]
		public string ehliyetTip
		{
			get
			{
				return this._ehliyetTip;
			}
			set
			{
				if ((this._ehliyetTip != value))
				{
					this.OnehliyetTipChanging(value);
					this.SendPropertyChanging();
					this._ehliyetTip = value;
					this.SendPropertyChanged("ehliyetTip");
					this.OnehliyetTipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ehliyetTarih", DbType="Date")]
		public System.Nullable<System.DateTime> ehliyetTarih
		{
			get
			{
				return this._ehliyetTarih;
			}
			set
			{
				if ((this._ehliyetTarih != value))
				{
					this.OnehliyetTarihChanging(value);
					this.SendPropertyChanging();
					this._ehliyetTarih = value;
					this.SendPropertyChanged("ehliyetTarih");
					this.OnehliyetTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="VarChar(15)")]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_silmeDurumu", DbType="VarChar(1)")]
		public string silmeDurumu
		{
			get
			{
				return this._silmeDurumu;
			}
			set
			{
				if ((this._silmeDurumu != value))
				{
					this.OnsilmeDurumuChanging(value);
					this.SendPropertyChanging();
					this._silmeDurumu = value;
					this.SendPropertyChanged("silmeDurumu");
					this.OnsilmeDurumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="musteri_kira", Storage="_kiras", ThisKey="kimlikNo", OtherKey="kimlikNo")]
		public EntitySet<kira> kiras
		{
			get
			{
				return this._kiras;
			}
			set
			{
				this._kiras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="musteri_odeme", Storage="_odemes", ThisKey="kimlikNo", OtherKey="kimlikNo")]
		public EntitySet<odeme> odemes
		{
			get
			{
				return this._odemes;
			}
			set
			{
				this._odemes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kiras(kira entity)
		{
			this.SendPropertyChanging();
			entity.musteri = this;
		}
		
		private void detach_kiras(kira entity)
		{
			this.SendPropertyChanging();
			entity.musteri = null;
		}
		
		private void attach_odemes(odeme entity)
		{
			this.SendPropertyChanging();
			entity.musteri = this;
		}
		
		private void detach_odemes(odeme entity)
		{
			this.SendPropertyChanging();
			entity.musteri = null;
		}
	}
}
#pragma warning restore 1591
